# Generated by Django 3.2.5 on 2021-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil_ctf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('file', models.FileField(upload_to=None)),
                ('competition_start', models.DateTimeField()),
                ('session_start', models.TimeField()),
                ('session_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='challenges_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
